### ISSUE TITLE
Chore: Figure out how to use dockerhub as container image registry

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#375] opened 2021-12-17 18:48 UTC
Currently our install scripts are tailored towards configuring GCR as image registry. In bug https://github.com/cloudfoundry/cf-k8s-controllers/issues/347 I tried configuring dockerhub but failed. The reason was that image api urls being used by reconcilers were not ok with dockerhub and caused various errors. To me that means that the code implements certain GCR assumptions which from point of view is wrong.

The purpose of this chore is to figure out how one can configure dockerhub as image registry via only changing config values. This should eradicate any potential registry implementation assumptions from the code.

**Comment by akrishna90** [comment] 2022-06-09 17:48
Duplicate of #1097 
Addressed in PR - #1168

**Closed by akrishna90** 2022-06-09 17:48 UTC
Labels: chore
