### ISSUE TITLE
[Bug]: Create Organization results in unauthorized create namespace

### ISSUE THREAD

**Issue by thomas-ej-worm** [cloudfoundry/korifi#3545] opened 2024-10-22 23:57 UTC
### What happened?

I installed Korifi as described in the `INSTALL.md` on a local RKE cluster. Korifi fails to create an organization. The `CfOrg` resource reports an error on creating a namespace:

```
Name:         cf-org-69d4e347-a44f-43bd-af02-af35e2242af4
Namespace:    cf
Labels:       <none>
Annotations:  korifi.cloudfoundry.org/creation-version: v0.13.0
API Version:  korifi.cloudfoundry.org/v1alpha1
Kind:         CFOrg
Metadata:
  Creation Timestamp:  2024-10-22T23:26:43Z
  Finalizers:
    cfOrg.korifi.cloudfoundry.org
  Generation:        1
  Resource Version:  643067
  UID:               a694adfa-53be-472a-ad2c-6691ee8294d7
Spec:
  Display Name:  test
Status:
  Conditions:
    Last Transition Time:  2024-10-22T23:26:44Z
    Message:               error creating namespace: admission webhook "rancher.cattle.io.namespaces.create-non-kubesystem" denied the request: Unauthorized
    Observed Generation:   1
    Reason:                Unknown
    Status:                False
    Type:                  Ready
  GUID:                    cf-org-69d4e347-a44f-43bd-af02-af35e2242af4
  Observed Generation:     1
Events:                    
```

### What you expected to happen

I expected to get a new organization.

### Acceptance Criteria

GIVEN a fresh installation of Korifi in RKE cluster
WHEN I login and create an organization
THEN I it should create an organization without error.

### How to reproduce it (as minimally and precisely as possible)

Install Korifi on a RKE cluster and create an organization.

### Environment

Revision of codebase: v0.13.0
Kubernetes version (use `kubectl version`): v1.30.4+rke2r1
Cloud provider or hardware configuration: RKE2
Others:

**Comment by thomas-ej-worm** [comment] 2024-10-23 00:19
I found these labels on the created `cf` and `korifi` namespaces and removed them:

```
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: restricted
```

But this does not solve the problem.

**Comment by thomas-ej-worm** [comment] 2024-10-24 17:25
Adding verb `create` for `namespaces` to ClusterRole `korifi-api-system-role` even does not help.

**Comment by danail-branekov** [comment] 2024-10-24 17:36
Hey @thomas-ej-worm 

I have no experience with RKE clusters. Are there any gotchas we need to keep in mind when spinning up a local test environment?

**Comment by thomas-ej-worm** [comment] 2024-10-24 17:52
It should be easy to setup a local test environment (for example in a VM):

**Requirements:**
- Docker installed

**Steps:;**
1. Start Rancher Server  
    `docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:latest`
2. Open the Rancher webinterface
3. Follow the instruction on login page to get admin bootstrap password from container logs.
4. After successful login in the webinterface you should see the clusters table. If not switch to "Clusters" in the navigation.
5. Click on "Create" (button on the right side above the table).
6. Choose "Custom".
7. After naming the cluster, accept the default settings with "Create" at end of page.
8. Rancher now tells you the command to setup the Kubernetes nodes. You can run this on the same machine where you started the Rancher Server docker container.
9. You successfully created a single node RKE2 cluster.
10. If you want to add further nodes, you can run same setup command.

**Comment by danail-branekov** [comment] 2024-10-24 21:43
> Which service account tries to create a namespace on org creation 
That is the controllers service account, see above

**Comment by thomas-ej-worm** [comment] 2024-10-24 22:49
Thanks, that helped:

After `kubectl edit clusterrole korifi-controllers-manager-role` and appending:

```
- apiGroups:
  - management.cattle.io
  resources:
  - projects
  verbs:
  - updatepsa
```

the CLI can successfully create an organization.

Can it be added to the helm charts or would this cause problems with installations on non RKE2-clusters?

**Comment by thomas-ej-worm** [comment] 2024-10-24 23:26
It seems RKE2 needs additional setup for Korifi. When pushing a test app the admission webhook denies the creation of a build pod:

```
{"severity":"ERROR","timestamp":"2024-10-24T23:22:15.080557914Z","caller":"controller/controller.go:316","message":"Reconciler error","controller":"buildworkload","controllerGroup":"korifi.cloudfoundry.org","controllerKind":"BuildWorkload","BuildWorkload":{"name":"e88eaf21-780d-46a9-8202-b6b66474f349","namespace":"cf-space-28dafdd0-5166-4972-b9e2-3fd970fb0d37"},"namespace":"cf-space-28dafdd0-5166-4972-b9e2-3fd970fb0d37","name":"e88eaf21-780d-46a9-8202-b6b66474f349","reconcileID":"c1dac6ba-5f7a-4b9f-87ae-310218634e69","error":"admission webhook \"validation.webhook.kpack.io\" denied the request: validation failed: spec.cache.volume.size cannot be set without spec.cache.volume.storageClassName or a default StorageClass: ","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
```

**Comment by danail-branekov** [comment] 2024-10-25 00:55
> Thanks, that helped

Awesome!


> Can it be added to the helm charts or would this cause problems with installations on non RKE2-clusters?

Instead of altering the cluster role from the korifi helm chart, you could just create a new cluster role and bind the korifi controllers service account to it. Such a configuration is specific to RKE indeed and does not really make much sense in the helm chart.

**Comment by danail-branekov** [comment] 2024-10-25 01:02
> It seems RKE2 needs additional setup for Korifi. When pushing a test app the admission webhook denies the creation of a build pod:

The error this time is caused by the kpack webhook. Kpack seems to require a default storage class, and on some cluster there is none.
Have look at [this slack discussion](https://cloudfoundry.slack.com/archives/C0297673ASK/p1727133924885349?thread_ts=1726706220.494799&cid=C0297673ASK), David solved it for EKS.

**Comment by danail-branekov** [comment] 2024-10-25 01:10
@thomas-ej-worm as the initial issue with org creation has been resolved, I am closing the issue, feel free to reopen though.

The issue seems to be going into a discussion on getting Korifi running on RKE, and we will be more than happy to help. I would encourage you to have the discussion on the korifi-dev slack cannel though. There you would get quicker responses and, most importantly, support not only from us (Korifi maintainers), but also from the community. Maybe someone has already solved some of the issues you come across.
Once you manage to get Korifi running on RKE, I would encourage you to write a blog post about it, we could publish that on the CF blog. But let's take this on slack.

**Closed** 2024-10-25 01:16 UTC
Labels: bug

**Comment by thomas-ej-worm** [comment] 2024-10-25 02:01
Thanks. I solved the storage problem by installing Longhorn.

```
helm repo add longhorn https://charts.longhorn.io
helm repo update
helm upgrade -i longhorn longhorn/longhorn --namespace longhorn-system --create-namespace
```
